apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJnaGNyLmlvIjogewogICAgICAgICAgICAiYXV0aCI6ICJVM1Z3WlhJdFEyVnlaV0ZzT21kb2NGOXpWV3RCT0RjMGVEa3lZbU50VkZKdlVtNXNTRTFpT1ZOUFFqUnhZa1EwVldwVk9UQSIKICAgICAgICB9Cgl9Cn0=
type: kubernetes.io/dockerconfigjson
